sudo: required
services:
  - docker

before_install: 
  - docker build -t jeffyarias/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script: 
   - docker run -e CI=true jeffyarias/react-test npm test

after_success: 
  - docker build -t jeffyarias/multi-client ./client/Dockerfile.dev
  - docker build jeffyarias/multi-nginx ./nginx
  - docker build jeffyarias/multi-server ./server
  - docker build jeffyarias/multi-worker ./worker
# Loggin into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to the docker hub

  - docker push jeffyarias/multi-client
  - docker push jeffyarias/multi-nginx
  - docker push jeffyarias/multi-server
  - docker push jeffyarias/multi-worker
