language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t jeffyarias/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run jeffyarias/react-test npm test -- --coverage
  # - docker run -e CI=true jeffyarias/react-test npm test
   

after_success: 
  - docker build -t jeffyarias/multi-client ./client
  - docker build -t jeffyarias/multi-nginx ./nginx
  - docker build -t jeffyarias/multi-server ./server
  - docker build -t jeffyarias/multi-worker ./worker
# Loggin into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to the docker hub

  - docker push jeffyarias/multi-client
  - docker push jeffyarias/multi-nginx
  - docker push jeffyarias/multi-server
  - docker push jeffyarias/multi-worker
